### ISSUE TITLE
Calculation code smells

### ISSUE THREAD

**Issue by AwaitingIrindul** [PolytechLyon/isi3-tp2-visiteur-regnard-marchand-tp2#1]
Bonjour, 

Pour faire la question 4, ou il faut calculer la valeur de l'arbre, nous n'arrivons pas à trouver comment implémenter le code. Nous avons différentes solutions, mais aucune ne nous semble la meilleure. 

 - Solution 1 : 
On change  l'interface  `Visitable` pour qu'elle fasse `int visit(...)` au lieu de `void visit(...)`. Cependant cela nous fais changer beaucoup de code et ne semble pas respecter le principe Ouvert/Fermé. 

- Solution 2 : 
On crée une autre interface `VisitorWithValue`(name pending) qui elle aura les valeurs de retour directement. Comme on commence à avoir plusieurs type de visitor, et plusieurs visitor, on pourrait utiliser le design pattern `AbstractFactory`. 

- Solution 3 :
Peut être un système de visitorception... 

- Solution 4 :
*Black Magic*

**Comment by Slashgear** [comment]
Solution 2 peut être intéressante 😉 
Pensez aussi à l'usage des generic. Cela pourrait vous aider également.

**Comment by AwaitingIrindul** [comment]
Bonjour, 

Nous avons essayé l'option 2 avec de la généricité, seulement nous nous sommes confrontés à un problème. Il fallait également changer le contrat de `Visitable`. Nous avons donc décidé de générifier également Visitable et nous avons utilisé  des Optional pour éviter les soucis. Est-ce une bonne méthode ? Voir cd11b580dc753e6c2bc86376ac9c4efd600feb34 et 3c527fde58d4faa22cfd03a929bbdd8a3faabbd9

**Comment by Slashgear** [comment]
C'est très sympa mais regarder un peu les méthodes Des optionals. Vous
pouvez faire du fonctionnel avec IfPresent().orElse()

Le lun. 12 mars 2018 16:11, Mathieu Regnard <notifications@github.com> a
écrit :

**Comment by AwaitingIrindul** [comment]
Nous avons effectué les changements dans 7e04e34d9a8ab4a8b73407ffe7a982fbba85bb9d.
