### ISSUE TITLE
Code review 

### ISSUE THREAD

**Issue by AwaitingIrindul** [PolytechLyon/isi3-tp2-visiteur-regnard-marchand-tp2#2]
Bonjour, 

Peut-on avoir une revue de code ?

**Comment by Slashgear** [comment]
- Un petit conseil, il faut fouiller la doc de Java quand vous arrivez à imaginer qu'il fasse recoder une simple Pair.
<details>
      <summary>SPOILER</summary>
      ÇA EXISTE!
</details>

- Pouvez vous m'expliquer le cas d'utilisation du pattern visiteur ?

- On range les choses en packages (:warning:  les packages en java c'est en minuscule)

- Votre utilisation des generic est *Attentio jugement perso* peut être un peu trop **overkill**. Je dirais YAGNI. mais ça fait le café donc laissons comme ça.

**Comment by SimonMarchand** [comment]
- [x] Un petit conseil, il faut fouiller la doc de Java quand vous arrivez à imaginer qu'il fasse recoder une simple 

- [ ] Pouvez vous m'expliquer le cas d'utilisation du pattern visiteur ?

<details>
      <summary>OUI</summary>
      On utilise le pattern visiteur lorsque l'on souhaite apporter une (et en général plusieurs) nouvelle fonctionnalité à une classe sans la modifier. Dans notre Use Case on ne souhaite pas modifier le (nouveau et en minuscule) package `graph` car il représente un model de conception de données et ne dépend pas des techniques de parcours. Les différents parcours utilisant le même modèle, les spécifications peuvent être apportées à un visiteur qui spécifiera lui même sa démarche de parcours.
</details>

- [x] On range les choses en packages (⚠️ les packages en java c'est en minuscule)

- [ ] Votre utilisation des generic est Attentio jugement perso peut être un peu trop overkill. Je dirais YAGNI. mais ça fait le café donc laissons comme ça.
<details>
<summary>Noté</summary>

![image](https://user-images.githubusercontent.com/13983294/37555995-5ecee4c6-29f0-11e8-9824-9e533f671e54.png)
</details>

**Comment by Slashgear** [comment]
Pour la définition du use case du visiteur c'est pas exactement ça.

La vrai définition est ici : http://java-design-patterns.com/patterns/visitor/

Votre utilisation de la balise detail =

![mindblown](https://media.giphy.com/media/Um3ljJl8jrnHy/giphy.gif)
